name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  ficonsax: ^0.0.3
  get: ^4.6.6
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  local_auth: ^2.3.0
  internet_connection_checker_plus: ^2.7.1
  mockito: ^5.4.5
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.8
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/font/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/font/nunito/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/font/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/font/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/font/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

flutter_intl:
    enabled: true
